# CC BY 4.0 Frank Schultz, Nara Hahn, https://github.com/spatialaudio/wfs_chapter_hda
# conda env create -f environment.yml  --force
name: mywfs
channels:  # conda 22.9.0
  - conda-forge
  - defaults
dependencies:
  - python  # 3.10.6
  - pip  # 22.3
  - numpy  # 1.23.3
  - scipy  # 1.9.1
  - matplotlib  # 3.6.1
  - pydocstyle  # 6.1.1
  - pycodestyle  # 2.9.1
  - flake8  # 5.0.4
  - pip:
    - sfs==0.6.2
# packages in environment at /Users/fs446/opt/anaconda3/envs/mywfs:
#
# Name                    Version                   Build  Channel
# brotli                    1.0.9                h1c322ee_7    conda-forge
# brotli-bin                1.0.9                h1c322ee_7    conda-forge
# bzip2                     1.0.8                h3422bc3_4    conda-forge
# ca-certificates           2022.9.24            h4653dfc_0    conda-forge
# certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
# contourpy                 1.0.5           py310h2887b22_0    conda-forge
# cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
# flake8                    5.0.4              pyhd8ed1ab_0    conda-forge
# fonttools                 4.37.4          py310h8e9501a_0    conda-forge
# freetype                  2.12.1               hd633e50_0    conda-forge
# importlib-metadata        4.11.4          py310hbe9552e_0    conda-forge
# jpeg                      9e                   he4db4b2_2    conda-forge
# kiwisolver                1.4.4           py310hd23d0e8_0    conda-forge
# lcms2                     2.12                 had6a04f_0    conda-forge
# lerc                      4.0.0                h9a09cb3_0    conda-forge
# libblas                   3.9.0           16_osxarm64_openblas    conda-forge
# libbrotlicommon           1.0.9                h1c322ee_7    conda-forge
# libbrotlidec              1.0.9                h1c322ee_7    conda-forge
# libbrotlienc              1.0.9                h1c322ee_7    conda-forge
# libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
# libcxx                    14.0.6               h2692d47_0    conda-forge
# libdeflate                1.14                 h1a8c8d9_0    conda-forge
# libffi                    3.4.2                h3422bc3_5    conda-forge
# libgfortran               5.0.0           11_3_0_hd922786_25    conda-forge
# libgfortran5              11.3.0              hdaf2cc0_25    conda-forge
# liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
# libopenblas               0.3.21          openmp_hc731615_3    conda-forge
# libpng                    1.6.38               h76d750c_0    conda-forge
# libsqlite                 3.39.4               h76d750c_0    conda-forge
# libtiff                   4.4.0                hfa0b094_4    conda-forge
# libwebp-base              1.2.4                h57fd34a_0    conda-forge
# libxcb                    1.13              h9b22ae9_1004    conda-forge
# libzlib                   1.2.13               h03a7124_4    conda-forge
# llvm-openmp               14.0.4               hd125106_0    conda-forge
# matplotlib                3.6.1           py310hb6292c7_0    conda-forge
# matplotlib-base           3.6.1           py310h78c5c2f_0    conda-forge
# mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
# munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
# ncurses                   6.3                  h07bb92c_1    conda-forge
# numpy                     1.23.3          py310h5d7c261_0    conda-forge
# openjpeg                  2.5.0                h5d4e404_1    conda-forge
# openssl                   3.0.5                h03a7124_2    conda-forge
# packaging                 21.3               pyhd8ed1ab_0    conda-forge
# pillow                    9.2.0           py310h173adc3_2    conda-forge
# pip                       22.3               pyhd8ed1ab_0    conda-forge
# pthread-stubs             0.4               h27ca646_1001    conda-forge
# pycodestyle               2.9.1              pyhd8ed1ab_0    conda-forge
# pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
# pyflakes                  2.5.0              pyhd8ed1ab_0    conda-forge
# pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
# python                    3.10.6          hae75cb6_0_cpython    conda-forge
# python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
# python_abi                3.10                    2_cp310    conda-forge
# readline                  8.1.2                h46ed386_0    conda-forge
# scipy                     1.9.1           py310ha0d8a01_0    conda-forge
# setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
# sfs                       0.6.2                    pypi_0    pypi
# six                       1.16.0             pyh6c4a22f_0    conda-forge
# snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
# tk                        8.6.12               he1e0b03_0    conda-forge
# tornado                   6.2             py310h02f21da_0    conda-forge
# tzdata                    2022e                h191b570_0    conda-forge
# unicodedata2              14.0.0          py310hf8d0d8f_1    conda-forge
# wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
# xorg-libxau               1.0.9                h27ca646_0    conda-forge
# xorg-libxdmcp             1.1.3                h27ca646_0    conda-forge
# xz                        5.2.6                h57fd34a_0    conda-forge
# zipp                      3.9.0              pyhd8ed1ab_0    conda-forge
# zstd                      1.5.2                h8128057_4    conda-forge
