# CC BY 4.0 Frank Schultz, Nara Hahn, https://github.com/spatialaudio/wfs_chapter_hda
name: sfs
channels:  # conda 25.5.1
  - conda-forge
  - defaults
dependencies:
  - python  # 3.13.5
  - pip  # 25.1.1
  - numpy  # 2.3.1
  - scipy  # 1.16.0
  - matplotlib  # 3.10.3
  - pydocstyle  # 6.3.0
  - pycodestyle  # 2.14.0
  - flake8  # 7.3.0
# needs sfs-python toolbox, see README.md
# packages in environment at /Users/fs446/miniconda/envs/sfs:
#
# Name                     Version          Build                 Channel
# appnope                    0.1.4            pyhd8ed1ab_1          conda-forge
# asttokens                  3.0.0            pyhd8ed1ab_1          conda-forge
# brotli                     1.1.0            h6e16a3a_3            conda-forge
# brotli-bin                 1.1.0            h6e16a3a_3            conda-forge
# bzip2                      1.0.8            hfdf4475_7            conda-forge
# ca-certificates            2025.7.9         hbd8a1cb_0            conda-forge
# colorama                   0.4.6            pyhd8ed1ab_1          conda-forge
# comm                       0.2.2            pyhd8ed1ab_1          conda-forge
# contourpy                  1.3.2            py313ha0b1807_0       conda-forge
# cycler                     0.12.1           pyhd8ed1ab_1          conda-forge
# debugpy                    1.8.14           py313h14b76d3_0       conda-forge
# decorator                  5.2.1            pyhd8ed1ab_0          conda-forge
# exceptiongroup             1.3.0            pyhd8ed1ab_0          conda-forge
# executing                  2.2.0            pyhd8ed1ab_0          conda-forge
# flake8                     7.3.0            pyhd8ed1ab_0          conda-forge
# fonttools                  4.58.5           py313h717bdf5_0       conda-forge
# freetype                   2.13.3           h694c41f_1            conda-forge
# importlib-metadata         8.7.0            pyhe01879c_1          conda-forge
# iniconfig                  2.0.0            pyhd8ed1ab_1          conda-forge
# ipykernel                  6.29.5           pyh57ce528_0          conda-forge
# ipython                    9.4.0            pyhfa0c392_0          conda-forge
# ipython_pygments_lexers    1.1.1            pyhd8ed1ab_0          conda-forge
# jedi                       0.19.2           pyhd8ed1ab_1          conda-forge
# jupyter_client             8.6.3            pyhd8ed1ab_1          conda-forge
# jupyter_core               5.8.1            pyh31011fe_0          conda-forge
# kiwisolver                 1.4.8            py313ha0b1807_1       conda-forge
# krb5                       1.21.3           h37d8d59_0            conda-forge
# lcms2                      2.17             h72f5680_0            conda-forge
# lerc                       4.0.0            hcca01a6_1            conda-forge
# libblas                    3.9.0            32_h7f60823_openblas  conda-forge
# libbrotlicommon            1.1.0            h6e16a3a_3            conda-forge
# libbrotlidec               1.1.0            h6e16a3a_3            conda-forge
# libbrotlienc               1.1.0            h6e16a3a_3            conda-forge
# libcblas                   3.9.0            32_hff6cab4_openblas  conda-forge
# libcxx                     20.1.7           hf95d169_0            conda-forge
# libdeflate                 1.24             hcc1b750_0            conda-forge
# libedit                    3.1.20250104     pl5321ha958ccf_0      conda-forge
# libexpat                   2.7.0            h240833e_0            conda-forge
# libffi                     3.4.6            h281671d_1            conda-forge
# libfreetype                2.13.3           h694c41f_1            conda-forge
# libfreetype6               2.13.3           h40dfd5c_1            conda-forge
# libgfortran                5.0.0            14_2_0_h51e75f0_103   conda-forge
# libgfortran5               14.2.0           h51e75f0_103          conda-forge
# libjpeg-turbo              3.1.0            h6e16a3a_0            conda-forge
# liblapack                  3.9.0            32_h236ab99_openblas  conda-forge
# liblzma                    5.8.1            hd471939_2            conda-forge
# libmpdec                   4.0.0            h6e16a3a_0            conda-forge
# libopenblas                0.3.30           openmp_hbf64a52_0     conda-forge
# libpng                     1.6.50           h3c4a55f_0            conda-forge
# libsodium                  1.0.20           hfdf4475_0            conda-forge
# libsqlite                  3.50.2           he7d56d0_0            conda-forge
# libtiff                    4.7.0            h1167cee_5            conda-forge
# libwebp-base               1.5.0            h6cf52b4_0            conda-forge
# libxcb                     1.17.0           hf1f96e2_0            conda-forge
# libzlib                    1.3.1            hd23fc13_2            conda-forge
# llvm-openmp                20.1.7           ha54dae1_0            conda-forge
# matplotlib                 3.10.3           py313habf4b1d_0       conda-forge
# matplotlib-base            3.10.3           py313he981572_0       conda-forge
# matplotlib-inline          0.1.7            pyhd8ed1ab_1          conda-forge
# mccabe                     0.7.0            pyhd8ed1ab_1          conda-forge
# munkres                    1.1.4            pyhd8ed1ab_1          conda-forge
# ncurses                    6.5              h0622a9a_3            conda-forge
# nest-asyncio               1.6.0            pyhd8ed1ab_1          conda-forge
# numpy                      2.3.1            py313hc518a0f_0       conda-forge
# openjpeg                   2.5.3            h7fd6d84_0            conda-forge
# openssl                    3.5.1            hc426f3f_0            conda-forge
# packaging                  25.0             pyh29332c3_1          conda-forge
# parso                      0.8.4            pyhd8ed1ab_1          conda-forge
# pexpect                    4.9.0            pyhd8ed1ab_1          conda-forge
# pickleshare                0.7.5            pyhd8ed1ab_1004       conda-forge
# pillow                     11.3.0           py313h0c4f865_0       conda-forge
# pip                        25.1.1           pyh145f28c_0          conda-forge
# platformdirs               4.3.8            pyhe01879c_0          conda-forge
# pluggy                     1.6.0            pyhd8ed1ab_0          conda-forge
# prompt-toolkit             3.0.51           pyha770c72_0          conda-forge
# psutil                     7.0.0            py313h63b0ddb_0       conda-forge
# pthread-stubs              0.4              h00291cd_1002         conda-forge
# ptyprocess                 0.7.0            pyhd8ed1ab_1          conda-forge
# pure_eval                  0.2.3            pyhd8ed1ab_1          conda-forge
# pycodestyle                2.14.0           pyhd8ed1ab_0          conda-forge
# pydocstyle                 6.3.0            pyhd8ed1ab_1          conda-forge
# pyflakes                   3.4.0            pyhd8ed1ab_0          conda-forge
# pygments                   2.19.2           pyhd8ed1ab_0          conda-forge
# pyparsing                  3.2.3            pyhd8ed1ab_1          conda-forge
# pytest                     8.4.1            pyhd8ed1ab_0          conda-forge
# python                     3.13.5           hc3a4c56_102_cp313    conda-forge
# python-dateutil            2.9.0.post0      pyhe01879c_2          conda-forge
# python_abi                 3.13             7_cp313               conda-forge
# pyzmq                      27.0.0           py313h2d45800_0       conda-forge
# qhull                      2020.2           h3c5361c_5            conda-forge
# readline                   8.2              h7cca4af_2            conda-forge
# scipy                      1.16.0           py313h7e69c36_0       conda-forge
# six                        1.17.0           pyhd8ed1ab_0          conda-forge
# snowballstemmer            3.0.1            pyhd8ed1ab_0          conda-forge
# stack_data                 0.6.3            pyhd8ed1ab_1          conda-forge
# tk                         8.6.13           hf689a15_2            conda-forge
# tomli                      2.2.1            pyhd8ed1ab_1          conda-forge
# tornado                    6.5.1            py313h63b0ddb_0       conda-forge
# traitlets                  5.14.3           pyhd8ed1ab_1          conda-forge
# typing_extensions          4.14.1           pyhe01879c_0          conda-forge
# tzdata                     2025b            h78e105d_0            conda-forge
# wcwidth                    0.2.13           pyhd8ed1ab_1          conda-forge
# xorg-libxau                1.0.12           h6e16a3a_0            conda-forge
# xorg-libxdmcp              1.1.5            h00291cd_0            conda-forge
# zeromq                     4.3.5            h7130eaa_7            conda-forge
# zipp                       3.23.0           pyhd8ed1ab_0          conda-forge
# zstd                       1.5.7            h8210216_2            conda-forge
